// SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { ButtonSection, ContentSection, AppHeader, HeadingLg, TextMd, TextSm,
         BasePage, PageBody, IconButton } from "@ui/widgets.slint";
import { Importance, Palette, Size } from "@ui/theme.slint";
import { Callbacks } from "../../callbacks.slint";
import { ImportReviewPageProps } from "./props.slint";
import { Navigate } from "../../gen/navigate.slint";
import { TR2, TrId } from "../../gen/tr.slint";
import { Liana } from "../../liana-theme.slint";
import { LianaButton } from "../../liana-widgets.slint";

export component ImportReviewPagePage inherits Rectangle {
    in property <ImportReviewPageProps> props;

    BasePage {
        VerticalLayout {
            AppHeader {
                title: TR2.lookup(TrId.ImportReviewTitle);
                side-padding: Size.sz6;
                IconButton {
                    icon: "chevron-left";
                    size: Size.sz8;
                    importance: Importance.normal;
                    clicked => {
                        Callbacks.cancel-import();
                        Navigate.backward();
                    }
                }
                Rectangle { }
            }

            PageBody {
                p-x: Size.sz4;
                p-y: Size.sz4;
                ContentSection {
                    spacing: Size.sz3;

                    HorizontalLayout {
                        alignment: center;
                        Image {
                            source: @image-url("../../../resources/liana-mark.svg");
                            width: 72px;
                            height: 86px;
                            image-fit: contain;
                        }
                    }

                    HeadingLg { text: TR2.lookup(TrId.ImportReviewNewWallet); horizontal-alignment: center; }
                    HorizontalLayout {
                        alignment: center;
                        spacing: Size.sz2;
                        TextSm { text: Callbacks.detail-network; color: Liana.green; }
                        TextSm { text: Callbacks.detail-checksum; color: Palette.content-tertiary; }
                    }

                    TextMd {
                        text: TR2.lookup(TrId.ImportReviewBody);
                        color: Palette.content-secondary;
                        horizontal-alignment: center;
                        wrap: word-wrap;
                    }

                }

                ButtonSection {
                    LianaButton {
                        label: TR2.lookup(TrId.CommonButtonContinue);
                        primary: true;
                        clicked => { Navigate.import-name-page({ }); }
                    }
                }
            }
        }
    }
}
