// SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { AppHeader, TextSm, TextMd, BasePage, PageBody, IconButton } from "../../compat/widgets.slint";
import { Importance, Palette, Size } from "../../compat/theme.slint";
import { Callbacks } from "../../callbacks.slint";
import { DescriptorQrPageProps } from "./props.slint";
import { Navigate } from "../../gen/navigate.slint";
import { TR2, TrId } from "../../gen/tr.slint";
import { Liana } from "../../liana-theme.slint";
import { LianaDynamicQrCode } from "../../liana-dynamic-qr.slint";

export component DescriptorQrPagePage inherits Rectangle {
    in property <DescriptorQrPageProps> props;

    BasePage {
        VerticalLayout {
            AppHeader {
                title: TR2.lookup(TrId.DescriptorQrTitle);
                side-padding: Size.sz6;
                IconButton {
                    icon: "chevron-left";
                    size: Size.sz8;
                    importance: Importance.normal;
                    clicked => { Navigate.backward(); }
                }
                Rectangle { }
            }

            PageBody {
                p-x: Size.sz4;
                VerticalLayout {
                    spacing: Size.sz4;

                    TextMd {
                        text: TR2.lookup(TrId.DescriptorQrBody);
                        color: Palette.content-secondary;
                        horizontal-alignment: center;
                        wrap: word-wrap;
                    }

                    LianaDynamicQrCode {
                        get-parts(density) => {
                            Callbacks.policy-qr-parts(Callbacks.detail-id, density);
                        }
                    }

                    TextSm {
                        text: Callbacks.detail-checksum;
                        color: Liana.green;
                        horizontal-alignment: center;
                    }
                }
            }
        }
    }
}
