// SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { ButtonSection, ContentSection, AppHeader, TextMd, BasePage,
         PageBody, IconButton } from "@ui/widgets.slint";
import { Importance, Palette, Size } from "@ui/theme.slint";
import { Callbacks } from "../../callbacks.slint";
import { VerifyResponsePageProps } from "./props.slint";
import { Navigate } from "../../gen/navigate.slint";
import { TR2, TrId } from "../../gen/tr.slint";
import { LianaButton } from "../../liana-widgets.slint";
import { LianaDynamicQrCode } from "../../liana-dynamic-qr.slint";

export component VerifyResponsePagePage inherits Rectangle {
    in property <VerifyResponsePageProps> props;

    BasePage {
        VerticalLayout {
            AppHeader {
                title: TR2.lookup(TrId.VerifyResponseTitle);
                side-padding: Size.sz6;
                IconButton {
                    icon: "chevron-left";
                    size: Size.sz8;
                    importance: Importance.normal;
                    clicked => { Navigate.backward(); }
                }
                Rectangle { }
            }

            PageBody {
                p-x: Size.sz4;
                ContentSection {
                    spacing: Size.sz3;
                    TextMd {
                        text: TR2.lookup(TrId.VerifyResponseBody);
                        color: Palette.content-secondary;
                        horizontal-alignment: center;
                        wrap: word-wrap;
                    }
                    LianaDynamicQrCode {
                        get-parts(density) => {
                            Callbacks.address-response-qr-parts(density);
                        }
                    }
                }
                ButtonSection {
                    LianaButton {
                        label: TR2.lookup(TrId.CommonButtonDone);
                        primary: true;
                        clicked => { Navigate.home-page({ }); }
                    }
                }
            }
        }
    }
}
