// SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { ButtonSection, ContentSection, AppHeader, HeadingLg, TextMd, TextSm,
         BasePage, PageBody, IconButton } from "@ui/widgets.slint";
import { Importance, Palette, Size } from "@ui/theme.slint";
import { Callbacks } from "../../callbacks.slint";
import { XpubFinishPageProps } from "./props.slint";
import { Navigate } from "../../gen/navigate.slint";
import { TR2, TrId } from "../../gen/tr.slint";
import { Liana } from "../../liana-theme.slint";
import { LianaButton } from "../../liana-widgets.slint";

export component XpubFinishPagePage inherits Rectangle {
    in property <XpubFinishPageProps> props;

    BasePage {
        VerticalLayout {
            AppHeader {
                title: TR2.lookup(TrId.XpubFinishTitle);
                side-padding: Size.sz6;
                IconButton {
                    icon: "chevron-left";
                    size: Size.sz8;
                    importance: Importance.normal;
                    clicked => { Navigate.backward(); }
                }
                Rectangle { }
            }

            PageBody {
                ContentSection {
                    spacing: Size.sz4;
                    HeadingLg {
                        text: TR2.lookup(TrId.XpubFinishHeading);
                        horizontal-alignment: center;
                    }
                    TextMd {
                        text: TR2.lookup(TrId.XpubFinishBody);
                        color: Palette.content-secondary;
                        horizontal-alignment: center;
                        wrap: word-wrap;
                    }
                    if Callbacks.import-error != "": TextSm {
                        text: Callbacks.import-error;
                        color: Liana.recovery;
                        horizontal-alignment: center;
                        wrap: word-wrap;
                    }
                }

                ButtonSection {
                    LianaButton {
                        label: TR2.lookup(TrId.HomeImportPolicy);
                        primary: true;
                        clicked => {
                            Callbacks.import-policy();
                            if Callbacks.import-parsed { Navigate.import-review-page({ }); }
                        }
                    }
                    LianaButton {
                        label: TR2.lookup(TrId.XpubFinishLater);
                        primary: false;
                        clicked => { Navigate.home-page({ }); }
                    }
                }
            }
        }
    }
}
