// SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Router } from "gen/router.slint";
import { Callbacks } from "callbacks.slint";
import { CurrentTheme, Images, Utils, Theme, UISize } from "compat/theme.slint";
import { TR } from "compat/i18n.slint";

export component AppWindow inherits Window {
    title: "Liana Signer";
    preferred-width: UISize.screen-width;
    preferred-height: UISize.screen-height;
    background: Theme.palette-background;
    Router { }
}

export * from "gen/exports.slint";
export { Callbacks, CurrentTheme, Images, Utils, TR, Theme }
